---
releases:
  - name: witness-revolution-whales
    namespace: witness-revolution-whales
    chart: ./charts/rsquared-witness
    values:
      - WITNESS_ID: {{ requiredEnv "WITNESS_ID" }}
      - WITNESS_PUB_KEY: {{ requiredEnv "WITNESS_PUB_KEY" }}
      - WITNESS_WIF_KEY: {{ requiredEnv "WITNESS_WIF_KEY" }}
